import { Vector3 } from "./geometry";

export interface Face {
  indices: number[];
  normal?: Vector3;
}

export class Mesh {
  public vertices: Vector3[] = [];
  public faces: Face[] = [];

  constructor(vertices: Vector3[] = [], faces: Face[] = []) {
    this.vertices = vertices;
    this.faces = faces;
  }

  /**
   * Calculates face normals for physical shading simulation
   */
  computeNormals(): void {
    this.faces.forEach(face => {
      if (face.indices.length < 3) return;
      const v0 = this.vertices[face.indices[0]];
      const v1 = this.vertices[face.indices[1]];
      const v2 = this.vertices[face.indices[2]];
      
      const edge1 = v1.sub(v0);
      const edge2 = v2.sub(v0);
      face.normal = edge1.cross(edge2).normalize();
    });
  }

  /**
   * Vertex Welding - Topological Repair (Inspired by MeshLab)
   * Collapses multiple vertices into one based on a spatial epsilon.
   */
  weld(epsilon: number = 0.01): void {
    const uniqueVertices: Vector3[] = [];
    const indexMap = new Map<number, number>();

    this.vertices.forEach((v, i) => {
      let found = -1;
      for (let j = 0; j < uniqueVertices.length; j++) {
        if (v.distanceTo(uniqueVertices[j]) < epsilon) {
          found = j;
          break;
        }
      }

      if (found === -1) {
        uniqueVertices.push(v);
        indexMap.set(i, uniqueVertices.length - 1);
      } else {
        indexMap.set(i, found);
      }
    });

    this.vertices = uniqueVertices;
    this.faces.forEach(face => {
      face.indices = face.indices.map(idx => indexMap.get(idx)!);
    });
    
    // Remove degenerate faces
    this.faces = this.faces.filter(f => new Set(f.indices).size >= 3);
  }

  /**
   * Laplacian Smoothing - Real-world mesh cleaning algorithm
   */
  smooth(iterations: number = 1): void {
    for (let iter = 0; iter < iterations; iter++) {
      const nextVertices = this.vertices.map((v, i) => {
        const neighbors = this.getNeighbors(i);
        if (neighbors.length === 0) return v;
        
        const sum = neighbors.reduce((acc, ni) => acc.add(this.vertices[ni]), Vector3.zero());
        return sum.mul(1 / neighbors.length);
      });
      this.vertices = nextVertices;
    }
  }

  private getNeighbors(vertexIndex: number): number[] {
    const neighbors = new Set<number>();
    this.faces.forEach(face => {
      const idx = face.indices.indexOf(vertexIndex);
      if (idx !== -1) {
        const prev = face.indices[(idx - 1 + face.indices.length) % face.indices.length];
        const next = face.indices[(idx + 1) % face.indices.length];
        neighbors.add(prev);
        neighbors.add(next);
      }
    });
    return Array.from(neighbors);
  }

  /**
   * Export to industrial Wavefront OBJ format
   */
  toOBJ(): string {
    let obj = "# Generated by PaperFabrik Compute\n";
    this.vertices.forEach(v => {
      obj += `v ${v.x.toFixed(4)} ${v.y.toFixed(4)} ${v.z.toFixed(4)}\n`;
    });
    this.faces.forEach(f => {
      obj += `f ${f.indices.map(i => i + 1).join(" ")}\n`;
    });
    return obj;
  }
}
